INSERT INTO person (full_name, email, phone) VALUES
('Roldán Sanjuan', 'cfalco@hervia.com', '555-1001'),
('María Pilar Verdejo', 'noguestere@yahoo.com', '555-1002'),
('Javi Sanmartín', 'trujillolola@hotmail.com', '555-1003'),
('Fermín Vendrell', 'maite89@hotmail.com', '555-1004'),
('Gabino Lobato', 'ncaceres@espada.net', '555-1005'),
('Carlos Haro', 'lara69@yahoo.com', '555-1006'),
('Daniela Sabater', 'rosario33@hotmail.com', '555-1007'),
('Modesta Amador', 'collvalentin@hidalgo-arnaiz.org', '555-1008'),
('Raimundo Toro', 'romacecilio@hotmail.com', '555-1009'),
('Joan Pedro', 'pinabaudelio@artigas.com', '555-1010'),
('Anna García', 'ponsfilomena@macias.es', '555-1011'),
('Vidal Ros', 'zsaenz@gmail.com', '555-1012'),
('Antonia Francisco', 'gironamirta@rosales-lopez.net', '555-1013'),
('Noemí Tejera', 'vbonilla@fuster.es', '555-1014'),
('Javiera Ayllón', 'mercedesmarino@yahoo.com', '555-1015'),
('Adela Bartolomé', 'tzaragoza@gmail.com', '555-1016'),
('José Mari Manjón', 'cfonseca@rico.com', '555-1017'),
('Lucio Mendez', 'brius@hotmail.com', '555-1018'),
('Nuria Hurtado', 'agatatellez@abascal.com', '555-1019'),
('Nilda Ortega', 'riosmodesto@hotmail.com', '555-1020'),
('Pedro Cerdá', 'donairerufina@jurado.com', '555-1021'),
('María Cristina Garcia', 'victorianomacias@cardona-vizcaino.org', '555-1022'),
('Pastor Carro', 'penasester@capdevila-lozano.es', '555-1023'),
('Emma Meléndez', 'adelia38@carlos.org', '555-1024'),
('Sabina Fabra', 'almudenaburgos@hotmail.com', '555-1025'),
('Evita Amo', 'qramis@orozco.es', '555-1026'),
('Telmo Alfonso', 'jafetbustos@hotmail.com', '555-1027'),
('Duilio Bosch', 'pozoinigo@gmail.com', '555-1028'),
('Manuelita Alberdi', 'clara32@yahoo.com', '555-1029'),
('Paloma Jaén', 'encarnacionchaparro@baez.com', '555-1030'),
('Paloma Coll', 'heracliocarbonell@tirado.com', '555-1031'),
('Emilio Riera', 'ruben71@yahoo.com', '555-1032'),
('Adalberto Arévalo', 'ellobet@gmail.com', '555-1033'),
('Felisa Rozas', 'filomenamontoya@fernandez.com', '555-1034'),
('Sebastián Pareja', 'antonia46@quintero.com', '555-1035'),
('Tomás Vilanova', 'barongracia@yahoo.com', '555-1036'),
('Angelita Moll', 'portillorufina@gmail.com', '555-1037'),
('Xiomara Peinado', 'ramiro53@yahoo.com', '555-1038'),
('Adora Castells', 'angelicapellicer@milla-romero.com', '555-1039'),
('Natalia Simó', 'casandra91@cortes.com', '555-1040'),
('Herminio Daza', 'egutierrez@garate.es', '555-1041'),
('Damián Campo', 'villalongajosep@yahoo.com', '555-1042'),
('Atilio Ordóñez', 'bribas@hotmail.com', '555-1043'),
('Javier Gómez', 'wenriquez@escudero.com', '555-1044'),
('Maricruz Arco', 'wvaldes@hotmail.com', '555-1045'),
('Marta Yáñez', 'camila70@hotmail.com', '555-1046'),
('Melchor Jurado', 'maria-luisavelasco@duque.org', '555-1047'),
('Diego Valenzuela', 'galollamas@acero.com', '555-1048'),
('Leyre Galindo', 'vicentemaristela@yahoo.com', '555-1049'),
('Augusto Cabrero', 'luciaasenjo@beltran-lobo.net', '555-1050');

INSERT INTO user (username, password, person_id) VALUES
( 'ana.lopez', 'pass123', 1),
( 'juan.perez', 'pass123', 2),
( 'luis.garcia', 'pass123', 3),
( 'marta.sanchez', 'pass123', 4),
('carlos.diaz', 'pass123', 5),
( 'laura.torres', 'pass123', 6),
( 'pedro.ramos', 'pass123', 7),
( 'sofia.castro', 'pass123', 8),
( 'jorge.vega', 'pass123', 9),
( 'elena.ruiz', 'pass123', 10);

INSERT INTO role ( name, description) VALUES
( 'Administrador', 'Acceso total al sistema'),
( 'Bibliotecario', 'Gestión de préstamos y devoluciones'),
( 'Estudiante', 'Acceso a préstamos personales'),
( 'Docente', 'Acceso extendido y gestión de reservas'),
( 'Invitado', 'Acceso limitado al catálogo'),
( 'Inspector', 'Revisión de movimientos'),
( 'Técnico', 'Mantenimiento del sistema'),
( 'Secretaría', 'Gestión administrativa'),
( 'Director', 'Visión general y estadísticas'),
( 'Soporte TI', 'Soporte técnico del sistema');

INSERT INTO role_user (user_id, role_id) VALUES
(1, 1),
(2, 2),
(3, 3),
(4, 4),
(5, 5),
(6, 6),
(7, 7),
(8, 8),
(9, 9),
(10, 10);

INSERT INTO module (name, description) VALUES
( 'Seguridad', 'Control de acceso y autenticación'),
( 'Gestión de Préstamos', 'Administración de libros prestados'),
( 'Catálogo', 'Visualización y búsqueda de libros'),
( 'Gestión de Usuarios', 'Manejo de usuarios y roles'),
( 'Configuración', 'Parámetros del sistema'),
( 'Historial', 'Consulta de préstamos anteriores'),
( 'Notificaciones', 'Envío de alertas a usuarios'),
( 'Estadísticas', 'Informes y métricas del sistema'),
( 'Mantenimiento', 'Gestión técnica de módulos'),
( 'Reservas', 'Manejo de reservas de libros');
INSERT INTO module_role (module_id, role_id) VALUES
(1, 1),
(2, 2),
(3, 3),
(4, 4),
(5, 1),
(6, 2),
(7, 10),
(8, 9),
(9, 7),
(10, 4);

INSERT INTO form ( name, url) VALUES
( 'Login', '/seguridad/login'),
( 'Nuevo Préstamo', '/prestamos/nuevo'),
( 'Ver Catálogo', '/catalogo/lista'),
( 'Registrar Usuario', '/usuarios/registro'),
( 'Configuración General', '/configuracion'),
( 'Historial Préstamos', '/historial'),
( 'Notificaciones', '/notificaciones'),
( 'Ver Estadísticas', '/estadisticas'),
( 'Módulos Técnicos', '/mantenimiento'),
( 'Reservar Libro', '/reservas/nueva');

INSERT INTO form_module (form_id, module_id) VALUES
(1, 1),
(2, 2),
(3, 3),
(4, 4),
(5, 5),
(6, 6),
(7, 7),
(8, 8),
(9, 9),
(10, 10);